### ISSUE TITLE
Unit test add.js

### ISSUE THREAD

**Issue by annikniem** [annikniem/COMP.SE.200-Assignment-Part-2#1]
In the scope of this issue, unit testing is done add.js utility library function.

**Comment by KashifR13** [comment]
![image](https://github.com/user-attachments/assets/5bf68d9f-b18e-4965-9d76-51a1a030d429)

**Comment by KashifR13** [comment]
![image](https://github.com/user-attachments/assets/02e24601-a786-4fe1-a7d6-7df3d164e98a)

**Comment by KashifR13** [comment]
![image](https://github.com/user-attachments/assets/2644ee22-fa1c-47e4-b56d-1494841190d3)
